#!/usr/bin/env python

from evernote.api.client import EvernoteClient

with open('evernote_PRIVATE_DEV_TOKEN', 'r') as f:
    user, dev_token = f.read().strip().split()

print user
print dev_token

client = EvernoteClient(token=dev_token.encode(encoding='ascii'), sandbox=True)

'''
user_store = client.get_user_store()
print(dir(user_store))
user = user_store.getUser()
print user.username
'''

note_store = client.get_note_store()
#notebooks = note_store.listNotebooks()

#for n in notebooks:
#    print n.name
